#!/bin/bash
# runs all predictions for Chile University data and saves results into respective folders

# exit when any command fails
set -e

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT

GIT_ROOT="$(git rev-parse --show-toplevel)"
GIT_ROOT=$GIT_ROOT"/FIGR"
PATH_TO_EXECUTABLE_DELTR=$GIT_ROOT/deltr-src
PATH_TO_EXECUTABLE_LISTNET=$GIT_ROOT/listnet-src
PATH_TO_ENGINEERING_DATASET=$GIT_ROOT/data/EngineeringStudents/NoSemiPrivate
RESULT_DIR=$GIT_ROOT/results/EngineeringStudents/NoSemiPrivate
TRAINING_SCORES_FILENAME=trainingScores_ORIG.pred
PREDICTIONS_FILENAME=predictions.pred
RERANKED_PREDICTIONS_FILENAME=predictions_ORIG.pred

##########################################################################################
# all gender predictions
##########################################################################################
for EXPERIMENT in gender highschool
do
	echo "###############################  Looping ... experiment $EXPERIMENT ############################### "
	echo ""
    for FOLD in fold_1 fold_2 fold_3 fold_4 fold_5
	do
        echo "$FOLD predictions..."
        cd $PATH_TO_EXECUTABLE_LISTNET
        # colorblind
        ./predict.m $PATH_TO_ENGINEERING_DATASET/$EXPERIMENT/$FOLD/chileDataL2R_${EXPERIMENT}_nosemi_fold${FOLD:5}_test.txt $RESULT_DIR/$EXPERIMENT/$FOLD/COLORBLIND/model.m $RESULT_DIR/$EXPERIMENT/$FOLD/COLORBLIND/

        # FIGR star
        ./predict.m $PATH_TO_ENGINEERING_DATASET/$EXPERIMENT/$FOLD/chileDataL2R_${EXPERIMENT}_nosemi_fold${FOLD:5}_test.txt $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED_FIGR/model.m $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED_FIGR/

        # FIGR PLUS
        ./predict.m $PATH_TO_ENGINEERING_DATASET/$EXPERIMENT/$FOLD/chileDataL2R_${EXPERIMENT}_nosemi_fold${FOLD:5}_test.txt $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED_FIGR_PLUS/model.m $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED_FIGR_PLUS/

         # FIGR MINUS
        ./predict.m $PATH_TO_ENGINEERING_DATASET/$EXPERIMENT/$FOLD/chileDataL2R_${EXPERIMENT}_nosemi_fold${FOLD:5}_test.txt $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED_FIGR_MINUS/model.m $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED_FIGR_MINUS/

        # FA*IR P-Star
        ./predict.m $PATH_TO_ENGINEERING_DATASET/$EXPERIMENT/$FOLD/chileDataL2R_${EXPERIMENT}_nosemi_fold${FOLD:5}_test.txt $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED/model.m $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED/

        # FA*IR P-Plus
        ./predict.m $PATH_TO_ENGINEERING_DATASET/$EXPERIMENT/$FOLD/chileDataL2R_${EXPERIMENT}_nosemi_fold${FOLD:5}_test.txt $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED_PPlus/model.m $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED_PPlus/

        # FA*IR P-MINUS
        ./predict.m $PATH_TO_ENGINEERING_DATASET/$EXPERIMENT/$FOLD/chileDataL2R_${EXPERIMENT}_nosemi_fold${FOLD:5}_test.txt $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED_PMinus/model.m $RESULT_DIR/$EXPERIMENT/$FOLD/PREPROCESSED_PMinus/

        cd $PATH_TO_EXECUTABLE_DELTR
        # DELTR gamma=0 --> LTR
        ./predict.m $PATH_TO_ENGINEERING_DATASET/$EXPERIMENT/$FOLD/chileDataL2R_${EXPERIMENT}_nosemi_fold${FOLD:5}_test.txt $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/model.m $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/

        # FIGR star
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$TRAINING_SCORES_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FIGR/$TRAINING_SCORES_FILENAME
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$PREDICTIONS_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FIGR/$RERANKED_PREDICTIONS_FILENAME

        # FIGR PLUS
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$TRAINING_SCORES_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FIGR_PLUS/$TRAINING_SCORES_FILENAME
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$PREDICTIONS_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FIGR_PLUS/$RERANKED_PREDICTIONS_FILENAME

        # FIGR MINUS
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$TRAINING_SCORES_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FIGR_MINUS/$TRAINING_SCORES_FILENAME
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$PREDICTIONS_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FIGR_MINUS/$RERANKED_PREDICTIONS_FILENAME

        # FA*IR P-Star
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$TRAINING_SCORES_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FA-IR/P-Star/$TRAINING_SCORES_FILENAME
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$PREDICTIONS_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FA-IR/P-Star/$RERANKED_PREDICTIONS_FILENAME

        # FA*IR P-Plus
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$TRAINING_SCORES_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FA-IR/P-Plus/$TRAINING_SCORES_FILENAME
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$PREDICTIONS_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FA-IR/P-Plus/$RERANKED_PREDICTIONS_FILENAME

        # FA*IR P-MINUS
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$TRAINING_SCORES_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FA-IR/P-Minus/$TRAINING_SCORES_FILENAME
        cp $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=0/$PREDICTIONS_FILENAME $RESULT_DIR/$EXPERIMENT/$FOLD/FA-IR/P-Minus/$RERANKED_PREDICTIONS_FILENAME

        # DELTR small gamma
        ./predict.m $PATH_TO_ENGINEERING_DATASET/$EXPERIMENT/$FOLD/chileDataL2R_${EXPERIMENT}_nosemi_fold${FOLD:5}_test.txt $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=SMALL/model.m $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=SMALL/

        # DELTR large gamma
        ./predict.m $PATH_TO_ENGINEERING_DATASET/$EXPERIMENT/$FOLD/chileDataL2R_${EXPERIMENT}_nosemi_fold${FOLD:5}_test.txt $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=LARGE/model.m $RESULT_DIR/$EXPERIMENT/$FOLD/GAMMA\=LARGE/
    done
done
